version: "2"
services:
  proxy:
    image: bspjojo/docker-proxy:latest
    container_name: proxy
    ports:
     - "8090:80"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:rw
  web:
    image: nginx
    container_name: "web"
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  extra:
    image: nginx
    container_name: "extra"
    ports:
    - "8081:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80