version: "2"
services:
  proxy:
    image: bspjojo/docker-proxy:latest
    container_name: proxy
    ports:
     - "8090:80"
    environment:
      - VIRTUAL_HOST=whoami.localhost
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
  web:
    image: nginx
    container_name: "web"
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  api1:
    image: bspjojo/testing-api:latest
    environment:
      - PROXY_LOCATION=/api/service1
  api2:
    image: bspjojo/testing-api:latest
    environment:
      - PROXY_LOCATION=/api/service2
  extra:
    image: nginx
    container_name: "extra"
    environment:
    - PROXY_LOCATION=/,/app
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro